name: Test workflow
on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to show in the UI instead of 'name'
        description: 'Person to greet'
        required: true
        default: 'World'

    jobs:
      greet:
        name: Greet
        runs-on: ubuntu-latest
        steps:
          - name: Send greeting
            run: echo "Hello ${{ inputs.name }}"